### ISSUE TITLE
Elementlarga padding va margin berish

### ISSUE THREAD

**Issue by nameal010203** [darxanov/job-listings#6]
![image](https://user-images.githubusercontent.com/105722979/168963350-0a4ccc70-b61e-42c4-b297-a749306dbfed.png)
![image](https://user-images.githubusercontent.com/105722979/168964813-9ec91bb2-e5e3-44a6-b47e-44dc4961e142.png)
Malumotlarga berilgan margin ni main ni oziga padding oziga berish bilan xal qilsangiz yaxshi boladi

**Comment by darxanov** [comment]
Rahmat
